#!/bin/bash
rm *.c
rm *.o


cat list2|
while read file
 do
   Filename=$(find ../ -name *"${file}.c" | head -n1)
   shortname=$(echo "$Filename"| cut -d "/" -f3)
   echo -e "\e[36mCreating ${shortname} file\e[97m"
   main=$(($(cat $Filename | grep main | wc -l)))
   if [[ "$main" == "2" ]]
   then
       fun_name=$(echo $shortname | cut -d "." -f1 | cut -d "-" -f2)
       echo -e "Function name:\n${fun_name}"
       echo -e "File contains a main \npath $Filename"
       cat $Filename
       echo "generating new file"
       rm ./*$fun_name*
       echo '#include "holberton.h"' >> "${shortname}.c"
       echo "$(cat 'holberton.h' | grep ${fun_name})" >> "${shortname}.c"
       cat "${shortname}.c"
   else
       cp $Filename $shortname
   fi
done
