#!/bin/bash
cat list|cut -d "." -f1|
while read CD_KND
 do
   Filename=$(find ../ -name "${CD_KND}.c" | head -n1)
   echo "creating ${CD_KND} file"
   #cp "${Filename}" "${$(echo $Filename | cut -d "/" -f3)}"
   cp "${Filename}" "${CD_KND}.c"
   gcc -g -O -c "${CD_KND}.c" -o "${CD_KND}.o"
   ar rc libholberton.a "${CD_KND}.o"
done
gcc -fno-pie -g -O -c "_putchar.c" -o "_putchar.o"
ar rc libholberton.a "_putchar.o"
